---
- name: ansible palybook to test ansible vault
  hosts: all
  become: true
  vars_files:
    - vault-pass.yml
  tasks:
  - name: clone a repo
    git: 
      repo: https://nholuongut:{{ password }}@github.com/nholuongut/vault.git
      dest: /opt/ansadmin/test-vault
